---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "ddnsclient.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ddnsclient.matchLabels" . | nindent 4 }}
  ports:
    - name: webhook
      protocol: TCP
      port: 443
      targetPort: webhook
    - name: metrics
      protocol: TCP
      port: 8443
      targetPort: metrics
